drop table if exists member CASCADE;
create table member
(
    userid      bigint generated by default as identity,
    id          varchar(255),
    password    varchar(255),
    name        varchar(255),
    primary key (userid)
);